# Generated by Django 2.2.5 on 2019-09-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='sentiment_confidence',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
    ]
