# Generated by Django 2.2.5 on 2019-09-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20190904_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='News',
        ),
    ]
